apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: voting-ui
  name: voting-ui
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: voting-ui
    weight: 100
