apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: voting-ui
  name: voting-ui
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: voting-ui
