apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: basic-api-deploy-run
spec:
  inputs:
    resources:
    - name: source-repo
      resourceRef:
        name: cd-git-src

  serviceAccount: docker-auth-sa
  taskRef:
    name: basic-api-deploy
