apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: basic-ui-deploy-run
spec:
  inputs:
    resources:
    - name: workspace-git
      resourceRef:
        name: deploy-git
  serviceAccount: vote-deploy
  taskRef:
    name: basic-ui-deploy
  